### ISSUE TITLE
convert test to plain Test::More

### ISSUE THREAD

**Issue by daxim** [evalEmpire/Hash-StoredIterator#2]
The dep on Fennec pulls in a whole tail of other deps: http://deps.cpantesters.org/?module=Fennec&perl=any+version&os=any+OS

This makes it much more annoying or difficult to package perl5i > 2.10, and IMO not justified by Fennec benefit.

Please convert the H::SI test file to Test::More. It doesn't use any of the advanced Fennec features like parallelisation so it should be straight-forward, and grouping can also be achieved through subtest().

**Comment by schwern** [comment]
The tests were converted to Test2 which has a very small dep chain and all the benefits of Fennec.
https://github.com/evalEmpire/Hash-StoredIterator/commit/b38e10fbbf0dd62fb7b57cef33dc810ecbddf19d
